### PR TITLE
ENH: allow to pass a custom Penalty object to FISTA

### PR DESCRIPTION
**Pull request by fabianp**

### CODE REVIEW

**Comment by mblondel** [comment]
Great, merged! 

Did you need this for your research?

**Comment by fabianp** [comment]
Also, but this time its for some examples I'm preparing for pydata Paris next week. 

Also, I've ported to numba Condat's super-fast fussed lasso proximal operator: https://gist.github.com/fabianp/8b62d905ae254fadf763cf1909904e3a . According to my benchmarks it's marginally faster than Condat's C code distributed with the paper.

What is your opinion on adding this proximal operator to lightning and a soft dependency on numba (i.e. without numba the code would still run but would be much slower) ? I think this would be a very nice addition to numba that is not found in other ML packages.

**Comment by mblondel** [comment]
It would be a nice addition but I would rather convert the code to Cython for now.

We can discuss making numba a dependency later.

**Comment by fabianp** [comment]
OK. Note that numba would be a soft dependency, ie the code would still run
(slower) without it.

**Comment by mblondel** [comment]
I know but the performance without Numba would be horrible. 

In the future, we can try to port lightning to Numba.

**Pull request merged**
