### PR TITLE
[MRG] Use distutils for sdist, not setuptools

### PR DESCRIPTION
**Pull request by vene**
This fix should make sdist no longer include egg-info folder, which breaks windows builds.

### CODE REVIEW

**Comment by fabianp** [comment]
LGTM

There is a test failure on windows, but it doesn't seem related to this

**Comment by aldanor** [comment]
Any ideas why the test fails on windows? Could it be just `@xfail`ed on Windows temporarily?

**Comment by aldanor** [comment]
Does fix the hardcoded local paths that show up in appveyor build?

**Comment by vene** [comment]
Yes, although a new sdist release would have to be made.

**Comment by StrikerRUS** [comment]
Resolved the conflict with the `master` branch.

**Review by StrikerRUS — APPROVED** [review]
LGTM!

**Pull request merged**
