### PR TITLE
Avoid overflow in log loss calculation

### PR DESCRIPTION
**Pull request by aldanor**

### CODE REVIEW

**Comment by aldanor** [comment]
Python 3.5 / x64 failure on AppVeyor seems to be unrelated as it also happened in other recent PRs.

(btw someone care to fix it? also switch to 3.6 perhaps)

**Comment by aldanor** [comment]
@mblondel?

**Comment by mblondel** [comment]
Sorry for the delay! Thanks, merging!

Regarding the AppVeyor failure, I think @vene looked into it at some point but I don't remember what was the conclusion.

**Comment by vene** [comment]
I don't know off the top of my head what's up with that issue, but I just experienced it with the 0.5.0 release, so it is not introduced here.

**Pull request merged**
