### PR TITLE
Release `0.6.2`

### PR DESCRIPTION
**Pull request by StrikerRUS**
I believe Python `3.10` support that has been added recently (3afcb4a9967a0d9e3961acd967705e42a593e448) deserves new release of the package. In new release we'll upload wheels for Python `3.10` making users' life easier.

### CODE REVIEW

**Review by mblondel — APPROVED** [review]
Agreed! Thanks a lot!

**Comment by StrikerRUS** [comment]
I've just pushed commit with version update to indicate new development cycle directly into `master`: 216003c4beaa9b83300e10dfa86f81c7f605f4a1.

**Comment by StrikerRUS** [comment]
@fabianp Could you please help to upload generated artifacts to PyPI like you did it last time?
https://github.com/scikit-learn-contrib/lightning/releases/tag/0.6.2
#184

**Comment by mblondel** [comment]
Maybe we should automate the process like e.g. [here](https://github.com/google/jaxopt/blob/main/.github/workflows/publish_to_pypi.yml).

**Comment by fabianp** [comment]
yes, tha would be great

**Comment by StrikerRUS** [comment]
Yeah, great idea!
I'll be happy to implement it but firstly we need to setup [PyPI API token](https://pypi.org/help/#apitoken). Who has required rights for doing that?

**Comment by fabianp** [comment]
@StrikerRUS what is your pypi username? I'll add you to the owners on pypi

**Comment by StrikerRUS** [comment]
My PyPI profile: https://pypi.org/user/StrikerRUS/.

**Comment by fabianp** [comment]
just added you

**Comment by StrikerRUS** [comment]
> just added you

Thank you! Accepted.
Will add auto-uploading functionality this weekend and keep you posted.

**Comment by StrikerRUS** [comment]
Well, now along with GitHub Release new PyPI release is created after pushing new tag (I also modified tag matching regex a little bit to allow `.devN` and `.postN` releases: #195).
https://github.com/scikit-learn-contrib/lightning/blob/dbbe833963280e675c124bbd5caadfcb13d89bd7/.github/workflows/main.yml#L133-L142

I'm really sorry for some mess in commits but I was struggling with accidentally uploaded `.egg` files. And had to create `0.6.2.post0` release to test new changes. Hope that's OK.

**Pull request merged**
