### PR TITLE
[MRG] Build directly from cython sources

### PR DESCRIPTION
**Pull request by lesteve**
This uses the same approach as in scikit-learn:
* in development mode .cpp are built directly from cython sources
* in release mode you build from .cpp files this allow to build from a released .tar.gz without cython

As part of this commit the .cpp files have been removed from the repo.

### CODE REVIEW

**Comment by mblondel** [comment]
Awesome, thanks a lot!

LGTM. @fabianp can you take a second look and merge?

**Comment by fabianp** [comment]
looks good to me. merging

**Comment by casotto** [comment]
Hello,
I am a windows user that used to struggle to get a compiled version of lightning. 
After this change everything compiles without any problems.
FYI the only difference I noticed in the compiled files is on the `random_fast.cpp`, the other give the same results.

Thanks a lot @lesteve !
Mattia

**Comment by lesteve** [comment]
Glad to hear that @casotto !

**Pull request merged**
