### PR TITLE
Add citing information

### PR DESCRIPTION
**Pull request by fabianp**
I created a Zenodo entry so that the software is citable.

### CODE REVIEW

**Comment by mblondel** [comment]
Great idea! Could you also add the BiBTeX entry directly to the README file (so that people can just copy/paste it). Thanks!

**Comment by fabianp** [comment]
Done. Merging this.

**Comment by mblondel** [comment]
Great! Looking forward to a citation in your next paper ;-)

**Comment by mblondel** [comment]
vlad found that last and first names are in reverse order both in the
readme and on zenodo

**Pull request merged**
