### PR TITLE
better classes_ support

### PR DESCRIPTION
**Pull request by kmike**
* Added support for `classes_` attribute to AdaGradClassifier, LinearSVC, SDCAClassifier, and SVRGClassifier;
* tests for `classes_` attribute of other classifiers.

### CODE REVIEW

**Comment by mblondel** [comment]
LGTM. Thanks a lot for this PR!

@fabianp Can you have a look too?

**Comment by mblondel** [comment]
Alright, @fabianp seems to be busy. Merging!

@kmike Thanks again and keep the pull-requests coming ;)

**Comment by kmike** [comment]
Thanks @mblondel!

**Comment by fabianp** [comment]
sorry for the late reply, anyway great to see this merged :-)

**Pull request merged**
