### PR TITLE
FIX: add random_fast.pxd to setup.py

### PR DESCRIPTION
**Pull request by fabianp**

### CODE REVIEW

**Comment by fabianp** [comment]
Build is failing and its not clear why, I'm playing with it to figure it out.

**Comment by fabianp** [comment]
Fixed the error. Green light to merge if the build succeeds @mblondel ? (fix is trivial and doesn't add code)

**Comment by fabianp** [comment]
merging since I don't see any drawbacks to this trivial fix.

**Comment by fabianp** [comment]
@mblondel let me know if you don't agree with merging on trivial fixes or you prefer always to have +1 (although being just two I think the push responsibly on trivial fixes makes more sense)

**Comment by mblondel** [comment]
sure you only need my review for major changes

**Pull request merged**
