### PR TITLE
Recompile with new Cython

### LINKED ISSUE #153: build pb on python 3.9
we started to have build failures on python 3.9 in benchopt:

https://github.com/benchopt/benchmark_lasso/pull/18/checks?check_run_id=2128864808

thanks for taking a lot.

### PR DESCRIPTION
**Pull request by StrikerRUS**
Fixed #153.

Linking previous recompilation: #134.

Root cause:

> The `tp_print` slot of PyTypeObject has been removed. It was used for printing objects to files in Python 2.7 and before. Since Python 3.0, it has been ignored and unused. (Contributed by Jeroen Demeyer in bpo-36974.)
https://docs.python.org/dev/whatsnew/3.9.html#id3

https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_vectorcall_offset

Proof that it works:
https://github.com/BayesWitnesses/m2cgen/blob/979fbd8b1ae048f2a843f59e2c2755c75dd816ac/requirements-test.txt#L6
https://github.com/BayesWitnesses/m2cgen/pull/371/checks?check_run_id=2428248886

Gently ping @mblondel @MechCoder @zermelozf @fabianp @vene according to
> The project is indeed no longer actively maintained but hot fixes like this to follow the latest scikit-learn are very welcome.
    https://github.com/scikit-learn-contrib/lightning/pull/142#issuecomment-641549497

Also, I believe this hotfix deserves a new PyPI release to make this package compatible with Python 3.9.

Thanks for your time.

### CODE REVIEW

**Comment by mblondel** [comment]
Thanks @StrikerRUS! Is `random_fast.cpp` the only file that needed to be recompiled?

**Comment by StrikerRUS** [comment]
@mblondel Thanks for your response!

Yes. [`randomkit.h`](https://github.com/scikit-learn-contrib/lightning/blob/master/lightning/impl/randomkit/randomkit.h) and [`randomkit.c`](https://github.com/scikit-learn-contrib/lightning/blob/master/lightning/impl/randomkit/randomkit.c) are not produced via Cython but they are ordinary manually written files. And there are no any other C or CPP files in the repo.

**Comment by StrikerRUS** [comment]
TBH, I'm very familiar with Cython, but why `random_fast.cpp` is not produced on the fly like all other CPP files in `impl` folder from corresponding `*_fast.pyx` files?

**Comment by mblondel** [comment]
Good point. The cpp files used to be included and they got removed in f54f0415c30ba51805d91292c6f3205955de9560 by @lesteve. I think `random_fast.cpp` should be removed too, it's probably an omission.

**Pull request closed without merging**
