### PR TITLE
Recompiled with Cython 0.29.7

### PR DESCRIPTION
**Pull request by ZeerakW**
Rebuilt using Cython 0.29.7 as suggested in #132 :)

### CODE REVIEW

**Comment by ZeerakW** [comment]
Tests failed, seemingly for a small drop in performance of classifiers.

**Comment by vene** [comment]
Failures are very odd. Could they be due to a change in underlying numpy/scipy/sklearn instead? Let me see if I can trigger a build on master

**Comment by vene** [comment]
Triggered at https://travis-ci.org/scikit-learn-contrib/lightning/builds/520280093

**Comment by vene** [comment]
Failures seem present identically on master. It's odd, but unrelated to this PR.

Could you modify travis.yml to test on python3.7 instead of 3.6 so we confirm that this change indeed fixes it?

**Comment by ZeerakW** [comment]
3.7 fails with the same two errors but the issue with installing the package seem to be fixed. I can install using pip in a clean virtual environment.

**Comment by vene** [comment]
Thanks! Master should work now.

**Pull request merged**
